package enums

enum class TipoResiduo (name: String){
    RESTO("RESTO"),
    ENVASES("ENVASES"),
    VIDRIO("VIDRIO"),
    ORGANICA("ORGÁNICA"),
    PAPEL_Y_CARTÓN("PAPEL Y CARTON"),
    PUNTOS_LIMPIOS("PUNTOS LIMPIOS"),
    CARTÓN_COMERCIAL("CARTON COMERCIAL"),
    VIDRIO_COMERCIAL("VIDRIO COMRCIAL"),
    PILAS("PILAS"),
    ANIMALES_MUERTOS("ANIMALES MUERTOS"),
    RCD("RCD"),
    CONTENEDORES_DE_ROPA_USADA("CONTENEDORES DE ROPA USADA"),
    RESIDUOS_DEPOSITADOS_EN_MIGAS_CALIENTES("REIDUOS DEPOSITADOS EN MIGAS CALIENTES"),
    DESCONOCIDO ("DESCONOCIDO")
}